#=====================================================================================================================================================
#### Configuration de l'identité pour l'authentification sur Azure
## https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/main/config/crd/bases/infrastructure.cluster.x-k8s.io_azureclusteridentities.yaml
#======================================================================================================================================================

apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: AzureClusterIdentity
metadata:
  name: capz-cluster-identity
  namespace: capz-management-clusterclass
spec:
  type: WorkloadIdentity
  tenantID: ${AZURE_TENANT_ID}
  clientID: ${AZURE_CLIENT_ID}
  allowedNamespaces: {}
